Baskerville Addendums
baskerville-hpc/hpc-intro pull request #2
Opened 2022-08-24 15:02 UTC by jnywong

Baskerville specific addendums to Episodes 11, 12 and 13

2022-08-25 07:11 UTC, branfosj approved these changes

2022-08-25 09:08 UTC, JimMadge requested changes
Starting to take shape :+1:.

2022-08-25 09:08 UTC, JimMadge commented on _episodes/11-connecting.md
> +> under the `'Configure account / reset password'` link. and disregard the **s**ecure **c**o**p**y tool below.
```suggestion
> under the `'Configure account / reset password'` link and disregard the **s**ecure **c**o**p**y tool below.
```

2022-08-25 09:08 UTC, JimMadge commented on _episodes/11-connecting.md
> +You may be asked for your password, or a One Time Passcode for Multi Factor Authentication. Watch out: the characters you type after
```suggestion
You may be asked for your password, and/or a One Time Passcode for Multi Factor Authentication. Watch out: the characters you type after
```

I think if public-key authentication fails you are prompted for a password then the OTP.

2022-09-14 13:47 UTC, jnywong commented
@branfosj I've included Jim's changes and branch is ready to merge

2022-09-14 13:56 UTC, JimMadge approved these changes

2022-09-14 13:57 UTC, merged